server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: jgj-auth
          uri: lb://jgj-auth
          predicates:
            - Path=/jgj-auth/**
          filters:
            - StripPrefix=1
        - id: jgj-admin
          uri: lb://jgj-admin
          predicates:
            - Path=/jgj-admin/**
          filters:
            - StripPrefix=1
        - id: jgj-portal
          uri: lb://jgj-portal
          predicates:
            - Path=/jgj-portal/**
          filters:
            - StripPrefix=1
        - id: jgj-search
          uri: lb://jgj-search
          predicates:
            - Path=/jgj-search/**
          filters:
            - StripPrefix=1
        - id: jgj-demo
          uri: lb://jgj-demo
          predicates:
            - Path=/jgj-demo/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/jgj-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 192.168.10.193
    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/jgj-auth/oauth/token"
      - "/jgj-auth/rsa/publicKey"
      - "/jgj-search/**"
      - "/jgj-portal/sso/login"
      - "/jgj-portal/sso/register"
      - "/jgj-portal/sso/getAuthCode"
      - "/jgj-portal/home/**"
      - "/jgj-portal/product/**"
      - "/jgj-portal/brand/**"
      - "/jgj-admin/admin/login"
      - "/jgj-admin/admin/register"
      - "/jgj-demo/nacos/**"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
